"""Derive the office mini's ~/.codex/config.toml from the laptop's.

Usage: python3 mini-codex-config.py <laptop-config.toml> <mini-config.toml>
Prints the merged config on stdout. Called by mini-sync.

The laptop config is the source for every shared setting (model, reasoning,
TUI, features, MCP servers, skill-sync's exclusions). Two kinds of tables do
not travel:
- laptop-only: the ChatGPT desktop app's integrations (computer-use,
  node_repl, plugins, marketplaces, desktop) and their `notify` hook;
- runtime-owned: the tables Codex writes on each machine as it runs (project
  trust, hook trust, the model-nux counter). These are kept from the mini's
  current file, so a sync never erases a trust decision made there.

Text-level on purpose: tables are cut at header lines and copied verbatim, so
comments and formatting survive and no TOML writer is needed.
"""

import re
import sys

HEADER = re.compile(r"^\[\[?\s*([^\]]+?)\s*\]\]?\s*(#.*)?$")

LAPTOP_ONLY = (
    "mcp_servers.node_repl",
    "mcp_servers.computer-use",
    "plugins",
    "marketplaces",
    "desktop",
    "shell_environment_policy.set",
)
RUNTIME_OWNED = ("projects", "hooks.state", "tui.model_availability_nux")
DROP_TOP_KEYS = ("notify", "cli_auth_credentials_store")

PREAMBLE = [
    "# Generated by mini-sync from the laptop's config.toml. Edit the laptop's;",
    "# only project/hook trust and the model-nux counter are kept from here.",
    "# Keychain is locked in SSH sessions; keep auth in ~/.codex/auth.json.",
    'cli_auth_credentials_store = "file"',
]


def under(name, prefixes):
    return any(name == p or name.startswith(p + ".") for p in prefixes)


def split(text):
    """Return (top-level lines, [(table name, lines)]). Comment and blank
    lines directly above a header move down into that header's block."""
    top, blocks, cur = [], [], None
    for line in text.splitlines():
        m = HEADER.match(line)
        if m:
            lines = top if cur is None else cur[1]
            carry = []
            while lines and (not lines[-1].strip() or lines[-1].lstrip().startswith("#")):
                carry.insert(0, lines.pop())
            cur = (m.group(1).strip(), carry + [line])
            blocks.append(cur)
        else:
            (top if cur is None else cur[1]).append(line)
    return top, blocks


def top_key(line):
    m = re.match(r"^\s*([A-Za-z0-9_-]+)\s*=", line)
    return m.group(1) if m else None


def drop_keys(lines, keys):
    """Remove `key = value` entries (including multi-line arrays)."""
    out, skipping, depth = [], False, 0
    for line in lines:
        if not skipping and top_key(line) in keys:
            depth = line.count("[") - line.count("]")
            skipping = depth > 0
            continue
        if skipping:
            depth += line.count("[") - line.count("]")
            skipping = depth > 0
            continue
        out.append(line)
    return out


def main(laptop_path, mini_path):
    with open(laptop_path) as f:
        top, blocks = split(f.read())
    try:
        with open(mini_path) as f:
            _, mini_blocks = split(f.read())
    except FileNotFoundError:
        mini_blocks = []

    body = drop_keys(top, DROP_TOP_KEYS)
    while body and not body[0].strip():
        body.pop(0)
    out = PREAMBLE + [""] + body
    for name, lines in blocks:
        if under(name, LAPTOP_ONLY) or under(name, RUNTIME_OWNED):
            continue
        out.extend(lines)
    for name, lines in mini_blocks:
        if under(name, RUNTIME_OWNED):
            # Drop the comments split() carried down from the line above:
            # in a generated file they belong to the laptop's tables.
            while lines and not HEADER.match(lines[0]):
                lines = lines[1:]
            out.extend([""] + lines)
    text = "\n".join(out)
    text = re.sub(r"\n{3,}", "\n\n", text).strip() + "\n"
    sys.stdout.write(text)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__.split("\n\n")[1])
    main(sys.argv[1], sys.argv[2])
